name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: grafana-snapshot-exporter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: ghcr.io/${{ github.repository_owner   }}/${{env.IMAGE_NAME}}:latest
